import type { Metadata } from "next";
import Link from "next/link";
import { getChampions } from "@/lib/data";
import { Container, SectionHeading } from "@/components/ui";
import pulse from "@/data/ladder_pulse.json";
import { Glyph, GLYPHS, Laurel } from "@/components/insignia";

// The ladder's record holders, measured from the top-50 boards the scraper
// walks: every crown belongs to a real player with a real sample behind it.
// Regenerated by scripts/build_ladder_pulse.py after each collection.
export const metadata: Metadata = {
  title: "Wild Rift Hall of Fame | Records from the EU Top 50 Boards",
  description:
    "The record holders across every Wild Rift champion leaderboard: most games, highest win rate, best KDA, most pentakills, MVP machines, guild power rankings and multi-board masters.",
  alternates: { canonical: "/hall-of-fame" },
};

type Feat = {
  value: number;
  player: string;
  champion: string;
  slug: string;
  detail: string;
} | null;

const hof = pulse.hallOfFame as Record<string, unknown> & {
  guilds: { guild: string; spots: number }[];
  multiBoard: { player: string; boards: { champion: string; slug: string; rank: number; wr: number; games: number }[] }[];
};

/* ---- engraved insignia, one per crown -------------------------------- */

/* title, blurb, glyph, accent and value format for every crown */
const CARDS: {
  key: string; title: string; blurb: string; glyph: string; tone: string;
  fmt: (v: number) => string;
}[] = [
  { key: "kdaKing", title: "The KDA King", blurb: "Best KDA, 30 games minimum", glyph: "gem", tone: "text-sky-300", fmt: (v) => `${v.toFixed(1)} KDA` },
  { key: "grinder", title: "The Grinder", blurb: "Most ranked games on one champion", glyph: "hourglass", tone: "text-amber-300", fmt: (v) => `${v.toLocaleString()} games` },
  { key: "mvpMachine", title: "The MVP Machine", blurb: "Highest MVP rate, 30 games minimum", glyph: "medal", tone: "text-gold", fmt: (v) => `${v.toFixed(1)}% of games` },
  { key: "quadraKing", title: "The Quadra Collector", blurb: "Most quadrakills on one champion", glyph: "cross", tone: "text-rose-300", fmt: (v) => `${v} quadrakills` },
  { key: "executioner", title: "The Executioner", blurb: "Most damage dealt per match", glyph: "swords", tone: "text-red-300", fmt: (v) => `${Math.round(v / 100) / 10}k damage` },
  { key: "wall", title: "The Wall", blurb: "Most damage soaked per match", glyph: "shield", tone: "text-emerald-300", fmt: (v) => `${Math.round(v / 100) / 10}k soaked` },
  { key: "demolition", title: "The Demolition Expert", blurb: "Most turret damage per match", glyph: "tower", tone: "text-orange-300", fmt: (v) => `${Math.round(v / 100) / 10}k to turrets` },
  { key: "economist", title: "The Economist", blurb: "Highest gold per minute, 30 games minimum", glyph: "coin", tone: "text-yellow-300", fmt: (v) => `${Math.round(v)} gold/min` },
  { key: "teamfighter", title: "The Frontliner", blurb: "Highest teamfight presence, 30 games minimum", glyph: "users", tone: "text-cyan-300", fmt: (v) => `${v.toFixed(1)}% of fights` },
  { key: "firstStriker", title: "The First Striker", blurb: "Highest first blood rate, 30 games minimum", glyph: "bolt", tone: "text-purple-300", fmt: (v) => `${v.toFixed(1)}% of games` },
  { key: "sCollector", title: "The S Collector", blurb: "Most S ratings on one champion", glyph: "award", tone: "text-indigo-300", fmt: (v) => `${v} S ratings` },
  { key: "legendKiller", title: "The Legend Killer", blurb: "Best Legendary Ranked win rate, 15 games minimum", glyph: "flame", tone: "text-rose-300", fmt: (v) => `${v.toFixed(1)}% in Legendary` },
  { key: "masteryRecord", title: "The Scholar", blurb: "Highest champion mastery score in EU", glyph: "scroll", tone: "text-teal-300", fmt: (v) => `${v.toLocaleString()} mastery` },
  { key: "veteran", title: "The Veteran", blurb: "Highest account level on any board", glyph: "hourglass", tone: "text-stone-300", fmt: (v) => `Level ${v}` },
];

export default function HallOfFamePage() {
  const byuSlug: Record<string, { icon: string; splash: string }> = {};
  for (const c of getChampions()) byuSlug[c.slug] = { icon: c.icon, splash: c.splash };

  const featured = ["pentaKing", "perfectionist"];
  const pentaKing = hof.pentaKing as Feat;
  const perfectionist = hof.perfectionist as Feat;
  const rest = CARDS.filter((c) => !featured.includes(c.key));

  return (
    <Container className="py-12">
      <div className="flex items-center gap-3">
        <Laurel />
        <div>
          <p className="text-xs font-semibold uppercase tracking-[0.25em] text-gold">EU ladder records</p>
          <h1 className="text-3xl font-semibold tracking-tight sm:text-4xl">Hall of Fame</h1>
        </div>
      </div>
      <p className="mt-3 max-w-2xl text-muted">
        Crowned from {pulse.nPlayers.toLocaleString()} top-50 players across{" "}
        {pulse.nChampions} champion boards, measured from their real ranked history.
        Every record has a name on it. Updated with every collection, last on {pulse.generatedAt}.
      </p>

      {/* the two thrones */}
      <div className="mt-8 grid gap-4 lg:grid-cols-2">
        {[{ feat: pentaKing, title: "The Penta King", blurb: "Most pentakills on a single champion", fmt: (v: number) => `${v} pentakills` },
          { feat: perfectionist, title: "The Perfectionist", blurb: "Highest win rate with 30 or more games", fmt: (v: number) => `${v.toFixed(1)}% win rate` }].map(({ feat, title, blurb, fmt }) => {
          if (!feat) return null;
          const art = byuSlug[feat.slug];
          return (
            <div key={title} className="relative overflow-hidden rounded-2xl border border-gold/30">
              {art && (
                <div className="absolute inset-0 bg-cover bg-center" style={{ backgroundImage: `url(${art.splash})` }} />
              )}
              <div className="absolute inset-0 bg-gradient-to-r from-bg via-bg/85 to-bg/40" />
              <div className="absolute inset-0 bg-gradient-to-t from-bg/95 via-transparent to-bg/30" />
              <div className="relative p-6">
                <div className="flex items-center gap-2 text-gold">
                  <Glyph d={GLYPHS.crown} className="text-gold" />
                  <span className="text-xs font-bold uppercase tracking-[0.2em]">{title}</span>
                </div>
                <p className="mt-0.5 text-xs text-faint">{blurb}</p>
                <p className="mt-4 text-4xl font-semibold tabular-nums text-gold">{fmt(feat.value)}</p>
                <div className="mt-3 flex items-center gap-2.5">
                  {art && (
                    // eslint-disable-next-line @next/next/no-img-element
                    <img src={art.icon} alt="" width={34} height={34}
                      className="h-[34px] w-[34px] rounded-full object-cover ring-2 ring-gold/50" />
                  )}
                  <div className="min-w-0">
                    <p className="truncate text-lg font-semibold">{feat.player || "Unknown player"}</p>
                    <p className="truncate text-xs text-muted">
                      <Link href={`/leaderboard?champion=${feat.slug}`} className="hover:text-text">{feat.champion}</Link>
                      {" "}from {feat.detail}
                    </p>
                  </div>
                </div>
              </div>
            </div>
          );
        })}
      </div>

      {/* the trophy wall */}
      <section className="mt-8">
        <div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-3">
          {rest.map(({ key, title, blurb, glyph, tone, fmt }) => {
            const feat = hof[key] as Feat;
            if (!feat) return null;
            const art = byuSlug[feat.slug];
            return (
              <div key={key} className="glass group relative overflow-hidden rounded-2xl p-5 transition hover:border-gold/30">
                <div className={`flex items-center gap-2 ${tone}`}>
                  <Glyph d={GLYPHS[glyph]} />
                  <span className="text-xs font-bold uppercase tracking-wide">{title}</span>
                </div>
                <p className="mt-0.5 text-[0.7rem] text-faint">{blurb}</p>
                <p className="mt-3 text-2xl font-semibold tabular-nums">{fmt(feat.value)}</p>
                <div className="mt-2 flex items-center gap-2">
                  {art && (
                    // eslint-disable-next-line @next/next/no-img-element
                    <img src={art.icon} alt="" width={28} height={28}
                      className="h-7 w-7 rounded-full object-cover ring-1 ring-white/15" />
                  )}
                  <div className="min-w-0">
                    <p className="truncate text-sm font-medium">{feat.player || "Unknown player"}</p>
                    <p className="truncate text-xs text-muted">
                      <Link href={`/leaderboard?champion=${feat.slug}`} className="hover:text-text">
                        {feat.champion}
                      </Link>
                      {" "}from {feat.detail}
                    </p>
                  </div>
                </div>
              </div>
            );
          })}
        </div>
      </section>

      <section className="mt-12">
        <SectionHeading title="Multi-board masters" subtitle="Players holding a top-50 spot on two or more champions at once" />
        <div className="glass overflow-x-auto rounded-2xl">
          <table className="w-full border-collapse text-sm sm:min-w-[480px]">
            <thead>
              <tr className="border-b border-line text-xs uppercase tracking-wide text-muted">
                <th className="px-4 py-3 text-left">Player</th>
                <th className="px-4 py-3 text-left">Boards</th>
              </tr>
            </thead>
            <tbody>
              {hof.multiBoard.map((m) => (
                <tr key={m.player} className="border-b border-line/60 last:border-0">
                  <td className="max-w-[160px] truncate px-4 py-2.5 font-medium">{m.player}</td>
                  <td className="px-4 py-2.5">
                    <span className="flex flex-wrap items-center gap-x-4 gap-y-1">
                      {m.boards.map((b) => (
                        <Link key={`${b.slug}-${b.rank}`} href={`/leaderboard?champion=${b.slug}`}
                          className="inline-flex items-center gap-1.5 text-muted transition hover:text-text">
                          {byuSlug[b.slug] && (
                            // eslint-disable-next-line @next/next/no-img-element
                            <img src={byuSlug[b.slug].icon} alt="" width={20} height={20}
                              className="h-5 w-5 rounded-full object-cover" />
                          )}
                          <span className="text-xs">
                            {b.champion} <span className="text-faint">#{b.rank}</span>
                          </span>
                        </Link>
                      ))}
                    </span>
                  </td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      </section>

      <section className="mt-12">
        <SectionHeading title="Guild power ranking" subtitle="Guilds holding the most top-50 spots across all boards" />
        <div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-5">
          {hof.guilds.map((g, i) => (
            <div key={g.guild} className="glass flex items-center justify-between rounded-xl px-4 py-3">
              <span className="flex items-center gap-2 truncate">
                {i < 3 ? (
                  <Glyph d={GLYPHS.crown} className={i === 0 ? "text-gold" : i === 1 ? "text-slate-300" : "text-amber-600"} />
                ) : (
                  <span className="w-[22px] text-center text-sm font-bold tabular-nums text-faint">{i + 1}</span>
                )}
                <span className="truncate text-sm font-medium">{g.guild}</span>
              </span>
              <span className="shrink-0 text-sm text-muted">{g.spots} spots</span>
            </div>
          ))}
        </div>
      </section>

      <p className="mt-10 text-xs text-faint">
        Records involving a rate require 30 or more ranked games, so a lucky handful of
        matches cannot take a crown. Accounts advertising boosting services are excluded
        from every record and from champion win rates: they play deliberately below their
        skill, so their numbers measure a mismatch rather than a player. Data comes from
        the in-game leaderboards and each player&apos;s ranked match history.
      </p>
    </Container>
  );
}
