import type { Metadata } from "next";
import Link from "next/link";
import { getChampions } from "@/lib/data";
import { Container, SectionHeading } from "@/components/ui";
import pulse from "@/data/ladder_pulse.json";

// The ladder's extremes, measured from the top-50 boards the scraper walks:
// every card is a real player with a real sample behind it. Regenerated by
// scripts/build_ladder_pulse.py after each collection.
export const metadata: Metadata = {
  title: "Wild Rift Hall of Fame | Records from the EU Top 50 Boards",
  description:
    "The record holders across every Wild Rift champion leaderboard: most games, highest win rate, best KDA, most pentakills, MVP machines, guild power rankings and multi-board masters.",
  alternates: { canonical: "/hall-of-fame" },
};

type Feat = {
  value: number;
  player: string;
  champion: string;
  slug: string;
  detail: string;
} | null;

const hof = pulse.hallOfFame as {
  grinder: Feat; perfectionist: Feat; kdaKing: Feat; pentaKing: Feat;
  mvpMachine: Feat; wall: Feat; demolition: Feat; veteran: Feat; freshest: Feat;
  guilds: { guild: string; spots: number }[];
  multiBoard: { player: string; boards: { champion: string; slug: string; rank: number; wr: number; games: number }[] }[];
};

const CARDS: { key: keyof typeof hof; title: string; blurb: string; fmt: (v: number) => string }[] = [
  { key: "grinder", title: "The Grinder", blurb: "Most ranked games on a single champion", fmt: (v) => `${v.toLocaleString()} games` },
  { key: "perfectionist", title: "The Perfectionist", blurb: "Highest win rate with 30 or more games", fmt: (v) => `${v.toFixed(1)}%` },
  { key: "kdaKing", title: "The KDA King", blurb: "Best KDA with 30 or more games", fmt: (v) => `${v.toFixed(1)} KDA` },
  { key: "pentaKing", title: "The Penta King", blurb: "Most pentakills on one champion", fmt: (v) => `${v} pentakills` },
  { key: "mvpMachine", title: "The MVP Machine", blurb: "Highest MVP rate with 30 or more games", fmt: (v) => `${v.toFixed(1)}% of games` },
  { key: "wall", title: "The Wall", blurb: "Most damage soaked per match", fmt: (v) => `${Math.round(v).toLocaleString()} taken` },
  { key: "demolition", title: "The Demolition Expert", blurb: "Most turret damage per match", fmt: (v) => `${Math.round(v).toLocaleString()} to turrets` },
  { key: "veteran", title: "The Veteran", blurb: "Highest account level on any board", fmt: (v) => `Level ${v}` },
  { key: "freshest", title: "The Prodigy", blurb: "Lowest account level to crack a top 50", fmt: (v) => `Level ${v}` },
];

export default function HallOfFamePage() {
  const icons: Record<string, string> = {};
  for (const c of getChampions()) icons[c.slug] = c.icon;

  return (
    <Container className="py-12">
      <h1 className="text-3xl font-semibold tracking-tight sm:text-4xl">Hall of Fame</h1>
      <p className="mt-2 max-w-2xl text-muted">
        The record holders across {pulse.nChampions} champion leaderboards: {" "}
        {pulse.nPlayers.toLocaleString()} top-50 players, measured from their real ranked
        history. Updated with every collection, last on {pulse.generatedAt}.
      </p>

      <section className="mt-8">
        <div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-3">
          {CARDS.map(({ key, title, blurb, fmt }) => {
            const feat = hof[key] as Feat;
            if (!feat) return null;
            return (
              <div key={key} className="glass rounded-2xl p-5">
                <p className="text-xs font-semibold uppercase tracking-wide text-accent">{title}</p>
                <p className="mt-0.5 text-[0.7rem] text-faint">{blurb}</p>
                <p className="mt-3 text-2xl font-semibold tabular-nums">{fmt(feat.value)}</p>
                <div className="mt-2 flex items-center gap-2">
                  {icons[feat.slug] && (
                    // eslint-disable-next-line @next/next/no-img-element
                    <img src={icons[feat.slug]} alt="" width={28} height={28}
                      className="h-7 w-7 rounded-full object-cover ring-1 ring-white/15" />
                  )}
                  <div className="min-w-0">
                    <p className="truncate text-sm font-medium">{feat.player || "Unknown player"}</p>
                    <p className="truncate text-xs text-muted">
                      <Link href={`/leaderboard?champion=${feat.slug}`} className="hover:text-text">
                        {feat.champion}
                      </Link>
                      {" "}from {feat.detail}
                    </p>
                  </div>
                </div>
              </div>
            );
          })}
        </div>
      </section>

      <section className="mt-12">
        <SectionHeading title="Multi-board masters" subtitle="Players holding a top-50 spot on two or more champions at once" />
        <div className="glass overflow-x-auto rounded-2xl">
          <table className="w-full border-collapse text-sm sm:min-w-[480px]">
            <thead>
              <tr className="border-b border-line text-xs uppercase tracking-wide text-muted">
                <th className="px-4 py-3 text-left">Player</th>
                <th className="px-4 py-3 text-left">Boards</th>
              </tr>
            </thead>
            <tbody>
              {hof.multiBoard.map((m) => (
                <tr key={m.player} className="border-b border-line/60 last:border-0">
                  <td className="max-w-[160px] truncate px-4 py-2.5 font-medium">{m.player}</td>
                  <td className="px-4 py-2.5">
                    <span className="flex flex-wrap items-center gap-x-4 gap-y-1">
                      {m.boards.map((b) => (
                        <Link key={b.slug} href={`/leaderboard?champion=${b.slug}`}
                          className="inline-flex items-center gap-1.5 text-muted transition hover:text-text">
                          {icons[b.slug] && (
                            // eslint-disable-next-line @next/next/no-img-element
                            <img src={icons[b.slug]} alt="" width={20} height={20}
                              className="h-5 w-5 rounded-full object-cover" />
                          )}
                          <span className="text-xs">
                            {b.champion} <span className="text-faint">#{b.rank}</span>
                          </span>
                        </Link>
                      ))}
                    </span>
                  </td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      </section>

      <section className="mt-12">
        <SectionHeading title="Guild power ranking" subtitle="Guilds holding the most top-50 spots across all boards" />
        <div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-5">
          {hof.guilds.map((g, i) => (
            <div key={g.guild} className="glass flex items-center justify-between rounded-xl px-4 py-3">
              <span className="flex items-center gap-2 truncate">
                <span className={`text-sm font-bold tabular-nums ${i < 3 ? "text-gold" : "text-faint"}`}>{i + 1}</span>
                <span className="truncate text-sm font-medium">{g.guild}</span>
              </span>
              <span className="shrink-0 text-sm text-muted">{g.spots} spots</span>
            </div>
          ))}
        </div>
      </section>

      <p className="mt-10 text-xs text-faint">
        Records require 30 or more ranked games where a rate is involved, so a lucky
        handful of matches cannot take a crown. Data comes from the in-game
        leaderboards and each player&apos;s ranked match history.
      </p>
    </Container>
  );
}
