"""Ask a model for each champion's highest-damage combo.

WHY THIS IS A SEPARATE FILE, not a field in ability_formulas.json:

    ability_formulas.json is derived -- re-running extract_formulas.py rewrites
    it. Its `combo` field is also the one thing in there that is NOT grounded in
    the tooltip text, and it was generated by a prompt asking for the "standard
    all-in burst sequence", which is a different question from the one the
    damage calculator needs. Asking the same model for the HIGHEST DAMAGE combo
    changed Xin Zhao's answer from a W-opener to an E-opener, which is what the
    kit actually wants.

    So combos live here, as an overlay, and survive re-extraction. Anything a
    player corrects can be pinned in the same file and will outrank the model.

Resumable: every champion is written as soon as it returns, so a rate limit
costs one call. Re-run with the same command to continue.

    python -m scripts.generate_combos            # all champions
    python -m scripts.generate_combos --only "Xin Zhao,Hecarim"
"""
from __future__ import annotations

import argparse
import json
import os
import sys
import time
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
OUT = ROOT / "data" / "champion_combos.json"
MODEL = "gemini-3.6-flash"

SYSTEM = ("You are a Wild Rift expert. Wild Rift is NOT League of Legends PC: abilities, "
          "cooldowns and items differ between the two games. Answer only about Wild Rift.")


def _load_key() -> str:
    for var in ("GEMINI_API_KEY", "GOOGLE_API_KEY"):
        if os.environ.get(var):
            return os.environ[var]
    env = ROOT / "web-next" / ".env.local"
    if env.exists():
        for line in env.read_text(encoding="utf-8").splitlines():
            if line.startswith(("GEMINI_API_KEY", "GOOGLE_API_KEY")):
                return line.split("=", 1)[1].strip()
    sys.exit("GEMINI_API_KEY is not set")


def champions() -> list[dict]:
    raw = json.loads((ROOT / "data" / "champions_wr.json").read_text(encoding="utf-8"))
    return list(raw.values()) if isinstance(raw, dict) else raw


def prompt_for(c: dict) -> str:
    kit = "\n".join(
        f"[{a['slot']}] {a['name']}: {' '.join((a.get('text') or '').split())[:300]}"
        for a in (c.get("abilities") or [])[:5])
    return (f"Champion: {c['name']} ({c.get('class', '?')}, {c.get('role', '?')})\n\n{kit}\n\n"
            f"What is the HIGHEST DAMAGE combo for {c['name']} in Wild Rift against a single "
            "champion target? Optimise purely for total damage dealt, not for safety or "
            "utility. Consider which abilities empower basic attacks, which reset the attack "
            "timer, and where basic attacks fit between casts.\n"
            'Use "P","1","2","3","4" for Passive/Q/W/E/R and "auto" for a basic attack. '
            "4 to 10 steps. Return JSON: "
            '{"combo": [...], "why": "two sentences on why this order maximises damage", '
            '"confidence": "high|medium|low"}')


VALID = {"P", "1", "2", "3", "4", "auto"}


def clean(combo) -> list[str]:
    """Keep only real steps, so a malformed answer cannot reach the engine."""
    if not isinstance(combo, list):
        return []
    out = [str(s).strip() for s in combo]
    out = [s for s in out if s in VALID]
    return out[:10] if len(out) >= 4 else []


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("--only", default="", help="comma-separated champion names")
    ap.add_argument("--model", default=MODEL)
    args = ap.parse_args()

    from google import genai
    from google.genai import types

    client = genai.Client(api_key=_load_key())
    config = types.GenerateContentConfig(
        system_instruction=SYSTEM, response_mime_type="application/json",
        temperature=0, max_output_tokens=8000)

    store = json.loads(OUT.read_text(encoding="utf-8")) if OUT.exists() else {
        "_source": f"{args.model}, asked for the highest-damage combo",
        "_note": ("Model-generated, not scraped. A human correction placed here outranks "
                  "it and is preserved: this file is never regenerated wholesale."),
        "champions": {},
    }
    done = store["champions"]

    wanted = [n.strip() for n in args.only.split(",") if n.strip()]
    todo = [c for c in champions()
            if (not wanted or c["name"] in wanted) and c["name"] not in done]
    print(f"{len(done)} already stored, {len(todo)} to fetch")

    for i, c in enumerate(todo, 1):
        try:
            r = client.models.generate_content(
                model=args.model, contents=prompt_for(c), config=config)
            got = json.loads(r.text)
        except Exception as exc:                                   # noqa: BLE001
            text = str(exc)
            if "RESOURCE_EXHAUSTED" in text or "429" in text:
                print(f"\nSTOPPED at {c['name']}: provider quota reached. "
                      f"{len(done)} stored so far; re-run to continue.")
                break
            print(f"  {c['name']}: failed, {text[:120]}")
            continue

        combo = clean(got.get("combo"))
        if not combo:
            print(f"  {c['name']}: unusable answer, skipped")
            continue
        done[c["name"]] = {
            "combo": combo,
            "why": str(got.get("why", ""))[:300],
            "confidence": got.get("confidence", ""),
        }
        OUT.write_text(json.dumps(store, indent=1, ensure_ascii=False), encoding="utf-8")
        print(f"  [{i}/{len(todo)}] {c['name']}: {' -> '.join(combo)}", flush=True)
        time.sleep(1)

    print(f"\n{len(done)} champions stored in {OUT.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
