"""Render the frontline validation report as a browsable local HTML artifact."""
from __future__ import annotations
import argparse
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
DEFAULT_REPORT = ROOT / "reports" / "engine_frontline_full_validation.json"
DEFAULT_OUT = ROOT / "reports" / "engine_frontline_full_validation.html"

HTML = r'''<!doctype html>
<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>Frontline engine validation</title>
<style>
:root{color-scheme:dark;--bg:#080d17;--panel:#101827;--line:#263853;--text:#eef4ff;--muted:#90a3bf;--blue:#49a9ff;--gold:#f5c75f;--green:#54d89b;--red:#ff7c8d}
*{box-sizing:border-box}html,body{margin:0;min-height:100%;background:radial-gradient(ellipse at 70% -20%,#1c3c62 0,#0c1422 42%,var(--bg) 78%);font:14px/1.45 Inter,ui-sans-serif,system-ui,-apple-system,Segoe UI,sans-serif;color:var(--text)}
button,input{font:inherit}button{color:inherit}.app{display:grid;grid-template-columns:272px minmax(0,1fr);min-height:100vh}
.sidebar{position:sticky;top:0;height:100vh;overflow:auto;padding:22px 16px;border-right:1px solid #20324d;background:#070d18dd;backdrop-filter:blur(20px)}.brand{display:flex;align-items:center;gap:11px;margin:0 6px 18px}.brand-mark{width:31px;height:31px;border-radius:10px;background:linear-gradient(140deg,#65c7ff,#3475ff);display:grid;place-items:center;font-size:13px;font-weight:900;color:#061224;box-shadow:0 8px 24px #288cff44}.brand strong{letter-spacing:.11em;font-size:12px}.brand small{display:block;color:var(--muted);font-size:10px;letter-spacing:.08em;margin-top:2px}
.sidebar input{width:100%;padding:10px 11px;border-radius:10px;border:1px solid var(--line);background:#0d1726;color:var(--text);outline:0}.sidebar input:focus{border-color:var(--blue)}.champions{display:grid;gap:4px;margin-top:14px}.champion-link{display:flex;align-items:center;gap:9px;width:100%;border:1px solid transparent;border-radius:10px;background:transparent;padding:7px 8px;text-align:left;cursor:pointer}.champion-link:hover{background:#16263d}.champion-link.active{background:linear-gradient(90deg,#1c3a5c,#16243a);border-color:#3977ad}.champion-link img{width:29px;height:29px;object-fit:cover;border-radius:8px}.champion-link span{min-width:0;overflow:hidden;text-overflow:ellipsis;white-space:nowrap}.champion-link em{margin-left:auto;color:var(--green);font-size:11px;font-style:normal}.empty{color:var(--muted);padding:10px}
.main{min-width:0;padding:28px clamp(18px,4vw,58px) 55px}.topbar{display:flex;justify-content:space-between;gap:20px;align-items:flex-start}.eyebrow{text-transform:uppercase;letter-spacing:.16em;color:var(--blue);font-weight:700;font-size:11px}.title{font-size:clamp(25px,4vw,42px);letter-spacing:-.04em;margin:5px 0 4px}.subtitle{color:var(--muted);max-width:760px;margin:0}.summary{display:grid;grid-template-columns:repeat(4,minmax(100px,1fr));gap:10px;margin:24px 0}.stat{padding:13px 15px;border:1px solid var(--line);border-radius:13px;background:linear-gradient(145deg,#142339,#0e1727);box-shadow:0 12px 26px #02060c44}.stat label{display:block;color:var(--muted);font-size:11px;text-transform:uppercase;letter-spacing:.09em}.stat strong{display:block;font-size:22px;margin-top:4px}.status-good{color:var(--green)}
.champion-head{display:flex;justify-content:space-between;align-items:center;gap:14px;margin-top:24px;padding:20px;border:1px solid var(--line);border-radius:18px;background:linear-gradient(145deg,#16263caa,#0e1727dd);box-shadow:0 17px 45px #02060c66}.champion-title{display:flex;align-items:center;gap:15px;min-width:0}.champion-title .champion-icon{width:64px;height:64px;border-radius:16px}.champion-title h2{margin:0;font-size:29px;letter-spacing:-.035em}.champion-title p{margin:4px 0 0;color:var(--muted)}.controls{display:flex;gap:8px;flex-wrap:wrap;justify-content:flex-end}.control{border:1px solid var(--line);background:#111e31;border-radius:9px;padding:9px 12px;cursor:pointer}.control:hover{border-color:#4d84b8;background:#172b44}.control:disabled{opacity:.4;cursor:not-allowed}
.bias-tabs{display:flex;gap:7px;margin:16px 0}.bias-tab{padding:9px 14px;border-radius:999px;border:1px solid var(--line);background:#0d1828;color:var(--muted);cursor:pointer}.bias-tab.active{color:#061424;background:var(--blue);border-color:var(--blue);font-weight:800}.bias-tab[data-bias="max_damage"].active{background:#ff9d71;border-color:#ff9d71}.bias-tab[data-bias="max_durability"].active{background:#81e1ad;border-color:#81e1ad}
.run-meta{display:flex;gap:8px;flex-wrap:wrap;color:var(--muted);font-size:12px;margin:0 0 14px}.tag{border:1px solid var(--line);border-radius:999px;padding:4px 8px;background:#0c1625}.tag.good{color:var(--green);border-color:#2a7259}.tag.warn{color:var(--gold);border-color:#735d25}.tag.bad{color:var(--red);border-color:#7a3042}
.build-grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(310px,1fr));gap:13px}.build-card{border:1px solid var(--line);border-radius:16px;background:linear-gradient(145deg,#15243a,#0e1726);padding:16px;box-shadow:0 15px 35px #02060c55}.build-card.best{border-color:#d9a84399;box-shadow:0 0 0 1px #d9a84333,0 18px 35px #02060c66}.build-top{display:flex;align-items:center;justify-content:space-between;gap:8px}.rank{font-weight:900;color:var(--gold);font-size:18px}.score{font-size:18px;font-weight:800}.score small{color:var(--muted);font-size:11px;font-weight:500}.archetype{color:var(--muted);font-size:11px;text-transform:uppercase;letter-spacing:.08em;margin:2px 0 12px}.item-row{display:flex;align-items:center;gap:6px;flex-wrap:wrap}.item,.champion-icon{position:relative;width:42px;height:42px;border-radius:9px;overflow:hidden;background:#1f2e45;border:1px solid #3c587b;display:grid;place-items:center}.item img,.champion-icon img{width:100%;height:100%;object-fit:cover}.champion-link .champion-icon{width:29px;height:29px;border-radius:8px}.item.fallback:after{content:attr(data-label);font-size:9px;text-align:center;padding:3px;color:#b9c7db}.item.boot{border-color:#9cc8f8}.arrow{color:#6f89a9}.order-label{font-size:11px;color:var(--muted);margin:13px 0 6px;text-transform:uppercase;letter-spacing:.08em}.rune-line{display:flex;gap:6px;align-items:center;flex-wrap:wrap;margin-top:13px}.rune{display:inline-flex;gap:5px;align-items:center;border:1px solid #314967;border-radius:999px;padding:4px 7px;background:#0b1523;color:#c3d2e8;font-size:11px}.rune img{width:17px;height:17px;border-radius:50%;object-fit:cover}.rune.tree{color:#8fc7ff}.rune.keystone{color:#ffd77e;border-color:#775d28}.identity{margin-top:12px;font-size:12px}.identity.good{color:var(--green)}.identity.bad{color:var(--red)}
.details{margin-top:15px;border-top:1px solid #20324b;padding-top:2px}.details summary{padding:12px 0;color:#a8c8ec;cursor:pointer;font-size:12px}.details-content{display:grid;gap:12px}.detail-block{border:1px solid #223754;border-radius:11px;padding:11px;background:#0b1422}.detail-block h4{margin:0 0 7px;font-size:12px;color:#bad1ed}.detail-block p{margin:3px 0;color:var(--muted);font-size:12px}.top-items{display:flex;flex-wrap:wrap;gap:5px}.mini-item{display:inline-flex;align-items:center;gap:4px;border-radius:8px;padding:3px 6px;background:#142237;color:#c9d8eb;font-size:11px}.mini-item .item{width:20px;height:20px;border-radius:4px}.mini-item .item:after{font-size:6px}.footer-note{color:var(--muted);font-size:12px;margin:22px 0 0}.kbd{font-family:ui-monospace,monospace;border:1px solid #38506e;background:#101f33;border-radius:5px;padding:1px 5px;color:#bfd7f2}
@media(max-width:850px){.app{grid-template-columns:1fr}.sidebar{position:relative;height:auto;border-right:0;border-bottom:1px solid #20324d;padding:14px}.brand{margin-bottom:12px}.champions{display:flex;overflow:auto;padding-bottom:3px}.champion-link{min-width:142px}.main{padding:20px 14px 45px}.topbar{display:block}.controls{justify-content:flex-start;margin-top:15px}.summary{grid-template-columns:repeat(2,1fr)}.champion-head{align-items:flex-start;display:block}.champion-title{margin-bottom:15px}.build-grid{grid-template-columns:1fr}}
@media(max-width:440px){.summary{gap:7px}.stat{padding:10px}.stat strong{font-size:18px}.champion-title h2{font-size:24px}.champion-title .champion-icon{width:52px;height:52px}}
</style></head><body>
<div class="app"><aside class="sidebar"><div class="brand"><div class="brand-mark">WR</div><div><strong>ENGINE REVIEW</strong><small>FRONTLINE VALIDATION</small></div></div><input id="filter" type="search" placeholder="Find a champion…" aria-label="Find a champion"><div id="champions" class="champions"></div></aside>
<main class="main"><div class="topbar"><div><div class="eyebrow">Production-equivalent engine audit</div><h1 class="title">Frontline build review</h1><p class="subtitle">Step through every bruiser and tank one at a time. Compare balanced, max-damage, and max-durability candidates with exact item order, boots, runes, and the search frontier behind each result.</p></div><div class="controls"><button class="control" id="prev">← Previous</button><button class="control" id="next">Next →</button></div></div><section class="summary" id="summary"></section><section id="viewer"></section><p class="footer-note">Tip: use <span class="kbd">←</span> <span class="kbd">→</span> to move between champions. This is a static snapshot generated from <code>engine_frontline_full_validation.json</code>.</p></main></div>
<script id="report" type="application/json">__REPORT__</script>
<script>
const report=JSON.parse(document.getElementById("report").textContent),runs=report.runs||[],champions=[...new Set(report.champions||runs.map(r=>r.champion))],biases=report.biases||["balanced","max_damage","max_durability"],labels={balanced:"Balanced",max_damage:"Max damage",max_durability:"Max durability"};
let state={champion:localStorage.getItem("frontlineChampion")||champions[0],bias:localStorage.getItem("frontlineBias")||biases[0]};
const slug=s=>String(s||"").toLowerCase().replace(/&/g,"and").replace(/[^a-z0-9]+/g,"-").replace(/^-|-$/g,""),pretty=s=>String(s||"").replace(/[-_]/g," ").replace(/\b\w/g,c=>c.toUpperCase()),esc=s=>String(s??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));
const itemSrc=s=>"../web-next/public/items/"+slug(s)+".webp", champSrc=s=>"../web-next/public/champions/"+slug(s)+".png";
function icon(s,kind,extra){let src=kind==="champion"?champSrc(s):itemSrc(s),label=esc(pretty(s)),klass=kind==="champion"?"champion-icon":"item";return '<span class="'+klass+' '+(extra||"")+'" data-label="'+label+'"><img src="'+src+'" alt="'+label+'" loading="lazy" onerror="this.parentElement.classList.add(\'fallback\');this.remove()"></span>'}
function rune(s,kind){let src=itemSrc(s),label=esc(s);return '<span class="rune '+(kind||"")+'"><img src="'+src+'" alt="" loading="lazy" onerror="this.remove()"><span>'+label+"</span></span>"}
function findRun(){return runs.find(r=>r.champion===state.champion&&r.bias===state.bias)}
function renderSummary(){let s=report.summary||{},m=((s.elapsedSeconds||0)/60).toFixed(1),a=[["Champions",champions.length],["Runs",(s.completedRuns||runs.length)+"/"+(s.expectedRuns||runs.length)],["Runtime",m+" min"],["Invalid top builds",s.invalidTopBuilds||0]];document.getElementById("summary").innerHTML=a.map((x,i)=>'<div class="stat"><label>'+x[0]+'</label><strong class="'+(i===3&&Number(x[1])===0?"status-good":"")+'">'+x[1]+"</strong></div>").join("")}
function renderSidebar(){let q=(document.getElementById("filter").value||"").toLowerCase(),el=document.getElementById("champions"),v=champions.filter(c=>c.toLowerCase().includes(q));el.innerHTML=v.length?v.map(c=>{let n=runs.filter(r=>r.champion===c&&r.validation&&r.validation.invalidTopBuilds===0).length;return '<button class="champion-link '+(c===state.champion?"active":"")+'" data-champion="'+esc(c)+'">'+icon(c,"champion")+'<span>'+esc(c)+"</span><em>"+n+"/"+biases.length+"</em></button>"}).join(""):'<div class="empty">No champions found</div>';el.querySelectorAll("[data-champion]").forEach(b=>b.onclick=()=>{state.champion=b.dataset.champion;persist();render()})}
function buildCard(b,i){let order=b.purchaseOrderProjection&&b.purchaseOrderProjection.length?b.purchaseOrderProjection:b.items||[],bad=b.identityErrors&&b.identityErrors.length,status=bad||b.valid===false?"Invalid":"Valid";return '<article class="build-card '+(i===0?"best":"")+'"><div class="build-top"><span class="rank">#'+(i+1)+'</span><span class="score">'+Number(b.score??0).toFixed(1)+' <small>score</small></span></div><div class="archetype">'+esc(b.archetype||"engine candidate")+'</div><div class="order-label">Item purchase order</div><div class="item-row">'+order.map((x,n)=>(n?'<span class="arrow">›</span>':"")+icon(x)).join("")+'</div><div class="order-label">Boots</div><div class="item-row">'+(b.boots?icon(b.boots,"item","boot"):'<span class="tag">not recorded</span>')+'</div><div class="rune-line">'+(b.runes?.keystone?rune(b.runes.keystone,"keystone"):"")+(b.runes?.primaryTree?rune(b.runes.primaryTree,"tree"):"")+(b.runes?.minors||[]).map(x=>rune(x)).join("")+(b.runes?.flex?rune(b.runes.flex):"")+'</div><div class="identity '+(status==="Valid"?"good":"bad")+'">'+(status==="Valid"?"✓ Identity and order checks passed":"⚠ "+(bad||[]).map(esc).join("; "))+"</div></article>"}
function details(r){let p=r.search?.paths||{};return '<details class="details"><summary>Search details · '+(r.search?.searched??"—")+' evaluations</summary><div class="details-content"><div class="detail-block"><h4>Candidate and scenario coverage</h4><p>Pool: '+(r.poolSize??"—")+' items · Candidate seeds: '+(r.candidateCount??"—")+' · Scenarios: '+(r.search?.scenarioEvaluations??"—")+' · Runtime: '+(r.seconds??"—")+'s</p><p>Objective: '+esc(r.search?.objective||"—")+' · Blend: '+(r.search?.blend?Math.round(r.search.blend.damage*100)+"% damage / "+Math.round(r.search.blend.survival*100)+"% survival":"—")+"</p></div>"+Object.entries(p).map(([name,x])=>'<div class="detail-block"><h4>'+esc(name)+" · "+esc(x.searchStrategy||x.poolMode||"search")+'</h4><p>Eligible '+(x.eligibleItems??"—")+' · Frontier '+(x.frontierItems??x.boundedPool??"—")+' · Legal combinations '+(x.legalCombinations??"—")+'</p><div class="top-items">'+(x.topItems||[]).map(y=>'<span class="mini-item">'+icon(y.item)+"<span>"+esc(pretty(y.item))+" · "+Number(y.score??0).toFixed(1)+"</span></span>").join("")+"</div></div>").join("")+"</div></details>"}
function renderViewer(){let r=findRun(),el=document.getElementById("viewer");if(!r){el.innerHTML='<div class="empty">No run found.</div>';return}let i=champions.indexOf(state.champion),none=!r.challenger;el.innerHTML='<section class="champion-head"><div class="champion-title">'+icon(state.champion,"champion")+'<div><h2>'+esc(state.champion)+'</h2><p>'+esc(r.class||"")+" · "+esc(r.role||"")+" · champion "+(i+1)+" of "+champions.length+'</p></div></div><div class="controls"><span class="tag good">'+(r.validation?.invalidTopBuilds===0?"All top builds valid":"Review validation flags")+"</span>"+(none?'<span class="tag warn">No stronger challenger</span>':"")+'</div></section><div class="bias-tabs">'+biases.map(b=>'<button class="bias-tab '+(b===state.bias?"active":"")+'" data-bias="'+b+'">'+(labels[b]||pretty(b))+"</button>").join("")+'</div><div class="run-meta"><span class="tag">'+(r.seconds??"—")+"s runtime</span><span class=\"tag\">"+(r.topEngineBuilds?.length||0)+" engine builds shown</span><span class=\"tag\">"+(r.search?.paths?Object.keys(r.search.paths).length:0)+" archetype paths</span>"+(r.challenger?.valid?'<span class="tag good">Challenger valid</span>':"")+"</div><div class=\"build-grid\">"+(r.topEngineBuilds||[]).map(buildCard).join("")+"</div>"+details(r);document.querySelectorAll("[data-bias]").forEach(b=>b.onclick=()=>{state.bias=b.dataset.bias;persist();render()})}
function persist(){localStorage.setItem("frontlineChampion",state.champion);localStorage.setItem("frontlineBias",state.bias)}
function render(){renderSummary();renderSidebar();renderViewer();let i=champions.indexOf(state.champion);document.getElementById("prev").disabled=i<=0;document.getElementById("next").disabled=i>=champions.length-1}
function move(d){let i=champions.indexOf(state.champion),n=champions[Math.max(0,Math.min(champions.length-1,i+d))];if(n&&n!==state.champion){state.champion=n;persist();render()}}
document.getElementById("filter").addEventListener("input",renderSidebar);document.getElementById("prev").onclick=()=>move(-1);document.getElementById("next").onclick=()=>move(1);document.addEventListener("keydown",e=>{if(e.target.matches("input"))return;if(e.key==="ArrowLeft")move(-1);if(e.key==="ArrowRight")move(1)});render();
</script></body></html>'''

def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--report", default=str(DEFAULT_REPORT))
    parser.add_argument("--out", default=str(DEFAULT_OUT))
    args = parser.parse_args()
    report = Path(args.report)
    out = Path(args.out)
    data = json.dumps(
        json.loads(report.read_text(encoding="utf-8")),
        ensure_ascii=False, separators=(",", ":"),
    ).replace("</", "<\\/")
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(
        HTML.replace("__REPORT__", data).replace(
            "engine_frontline_full_validation.json", report.name),
        encoding="utf-8",
    )
    print(f"Wrote {out} ({out.stat().st_size:,} bytes)")


if __name__ == "__main__":
    main()

