"use client";

import { useEffect, useState } from "react";

/**
 * Live "builds generated" figure.
 *
 * Every generation increments a server-side counter; this reads the total back
 * from /api/stats, which is cached at the edge for an hour. So the number does
 * move on its own, but a busy home page never costs more than one store read
 * per hour. Renders the fallback until the real figure lands, so the layout
 * never jumps.
 */
export function BuildsGeneratedCount({ fallback = "-" }: { fallback?: string }) {
  const [total, setTotal] = useState<number | null>(null);

  useEffect(() => {
    let cancelled = false;
    void (async () => {
      try {
        const res = await fetch("/api/stats");
        if (!res.ok || cancelled) return;
        const data = (await res.json()) as { buildsGenerated: number };
        if (typeof data.buildsGenerated === "number") setTotal(data.buildsGenerated);
      } catch {
        /* keep the fallback */
      }
    })();
    return () => {
      cancelled = true;
    };
  }, []);

  return <>{total == null ? fallback : total.toLocaleString()}</>;
}

/** Same figure, with a live dot, for the hero strip. */
export function BuildsGeneratedPill() {
  const [total, setTotal] = useState<number | null>(null);

  useEffect(() => {
    let cancelled = false;
    void (async () => {
      try {
        const res = await fetch("/api/stats");
        if (!res.ok || cancelled) return;
        const data = (await res.json()) as { buildsGenerated: number };
        if (typeof data.buildsGenerated === "number") setTotal(data.buildsGenerated);
      } catch {
        /* the pill simply stays hidden */
      }
    })();
    return () => {
      cancelled = true;
    };
  }, []);

  if (total == null || total < 1) return null;

  return (
    <span className="inline-flex items-center gap-1.5 rounded-full border border-accent/30 bg-accent/10 px-3 py-1 text-xs font-medium text-accent">
      <span className="h-1.5 w-1.5 rounded-full bg-accent motion-safe:animate-pulse" />
      {total.toLocaleString()} builds generated by players
    </span>
  );
}
