import Link from "next/link";
import { SectionHeading, Card } from "@/components/ui";
import pulse from "@/data/ladder_pulse.json";
import items from "@/data/items.json";

// What the freshly scraped top-50 boards agree on, aggregated across every
// champion collected so far. Regenerated by scripts/build_ladder_pulse.py.

type ChampProfile = {
  name: string; avgWr: number | null; kda: number | null; teamfight: number | null;
  gpm: number | null; dmgDealt: number | null; dmgTaken: number | null;
  turret: number | null; firstBlood: number | null; mvpRate: number | null;
  gamesMedian: number | null; legendaryTax: number | null; pentas: number;
};

function itemIconMap(): Record<string, string> {
  const map: Record<string, string> = {};
  for (const it of items as { slug: string; icon?: string }[]) {
    if (it.icon) map[it.slug] = it.icon;
  }
  return map;
}

function extreme(
  champs: [string, ChampProfile][],
  key: keyof ChampProfile,
  dir: "max" | "min" = "max",
): { slug: string; c: ChampProfile } | null {
  const rows = champs.filter(([, c]) => typeof c[key] === "number");
  if (!rows.length) return null;
  rows.sort((a, b) => (Number(b[1][key]) - Number(a[1][key])) * (dir === "max" ? 1 : -1));
  return { slug: rows[0][0], c: rows[0][1] };
}

export function LadderPulseSection({ championIcons }: { championIcons: Record<string, string> }) {
  const icons = itemIconMap();
  const champs = Object.entries(pulse.champions as Record<string, ChampProfile>);
  if (!champs.length) return null;

  const ksTotal = pulse.keystoneMeta.reduce((a, k) => a + k.count, 0);
  const spTotal = pulse.spellMeta.reduce((a, s) => a + s.count, 0);

  const extremes: { label: string; key: keyof ChampProfile; dir?: "max" | "min"; fmt: (v: number) => string }[] = [
    { label: "Highest damage", key: "dmgDealt", fmt: (v) => `${Math.round(v / 100) / 10}k per match` },
    { label: "Biggest tank", key: "dmgTaken", fmt: (v) => `${Math.round(v / 100) / 10}k soaked` },
    { label: "Turret menace", key: "turret", fmt: (v) => `${Math.round(v).toLocaleString()} to turrets` },
    { label: "Teamfight core", key: "teamfight", fmt: (v) => `${v.toFixed(1)}% presence` },
    { label: "First blood king", key: "firstBlood", fmt: (v) => `${v.toFixed(1)}% of games` },
    { label: "Richest", key: "gpm", fmt: (v) => `${Math.round(v)} gold per minute` },
  ];

  const taxRows = champs
    .filter(([, c]) => c.legendaryTax != null)
    .sort((a, b) => Number(b[1].legendaryTax) - Number(a[1].legendaryTax));

  const dedication = [...champs]
    .filter(([, c]) => c.gamesMedian != null)
    .sort((a, b) => Number(b[1].gamesMedian) - Number(a[1].gamesMedian));

  return (
    <div className="mt-10">
      <SectionHeading
        title="Ladder pulse"
        subtitle={`Measured from ${pulse.nPlayers.toLocaleString()} top-50 players and ${pulse.nBuilds.toLocaleString()} live builds across ${pulse.nChampions} freshly collected boards`}
        href="/leaderboard"
        linkLabel="Browse the boards"
      />

      <div className="grid gap-4 lg:grid-cols-2">
        <Card className="p-5">
          <p className="text-xs font-semibold uppercase tracking-wide text-muted">
            Most equipped items in high elo
          </p>
          <div className="mt-3 flex flex-wrap gap-3">
            {pulse.itemMeta.slice(0, 12).map((it) => (
              <span key={it.slug} className="flex flex-col items-center gap-1" title={it.name}>
                {icons[it.slug] ? (
                  // eslint-disable-next-line @next/next/no-img-element
                  <img src={icons[it.slug]} alt={it.name} width={34} height={34}
                    className="h-[34px] w-[34px] rounded-md border border-line/70 bg-black/30 object-cover" />
                ) : (
                  <span className="grid h-[34px] w-[34px] place-items-center rounded-md border border-line bg-white/5 text-[0.6rem] text-faint">?</span>
                )}
                <span className="text-[0.65rem] tabular-nums text-faint">{it.count}</span>
              </span>
            ))}
          </div>
        </Card>

        <Card className="p-5">
          <p className="text-xs font-semibold uppercase tracking-wide text-muted">
            Keystone meta share
          </p>
          <div className="mt-3 space-y-1.5">
            {pulse.keystoneMeta.slice(0, 6).map((k) => (
              <div key={k.name} className="flex items-center gap-2 text-sm">
                <span className="w-40 truncate">{k.name}</span>
                <span className="h-2 rounded-full bg-accent/70"
                  style={{ width: `${Math.max(3, (k.count / ksTotal) * 220)}px` }} />
                <span className="text-xs tabular-nums text-muted">
                  {Math.round((k.count / ksTotal) * 100)}%
                </span>
              </div>
            ))}
          </div>
          <p className="mt-4 text-xs font-semibold uppercase tracking-wide text-muted">Spell pairs</p>
          <p className="mt-1.5 text-sm text-muted">
            {pulse.spellMeta.slice(0, 3).map((s, i) => (
              <span key={s.pair}>
                {i > 0 && " · "}
                <span className="text-text">{s.pair}</span>{" "}
                <span className="text-xs text-faint">{Math.round((s.count / spTotal) * 100)}%</span>
              </span>
            ))}
          </p>
        </Card>
      </div>

      <div className="mt-4 grid gap-3 sm:grid-cols-2 lg:grid-cols-3">
        {extremes.map(({ label, key, dir, fmt }) => {
          const hit = extreme(champs, key, dir);
          if (!hit) return null;
          return (
            <Card key={label} className="flex items-center gap-3 p-4">
              {championIcons[hit.slug] && (
                // eslint-disable-next-line @next/next/no-img-element
                <img src={championIcons[hit.slug]} alt="" width={36} height={36}
                  className="h-9 w-9 rounded-full object-cover ring-1 ring-white/15" />
              )}
              <div className="min-w-0">
                <p className="text-[0.65rem] font-semibold uppercase tracking-wide text-muted">{label}</p>
                <p className="truncate text-sm font-medium">
                  <Link href={`/leaderboard?champion=${hit.slug}`} className="hover:text-accent">
                    {hit.c.name}
                  </Link>
                  <span className="ml-1.5 text-xs text-faint">{fmt(Number(hit.c[key]))}</span>
                </p>
              </div>
            </Card>
          );
        })}
      </div>

      <div className="mt-4 grid gap-4 lg:grid-cols-2">
        <Card className="p-5">
          <p className="text-xs font-semibold uppercase tracking-wide text-muted">
            The Legendary tax
          </p>
          <p className="mt-1 text-xs text-faint">
            How much win rate each champion&apos;s top players give up in Legendary Ranked.
          </p>
          <div className="mt-3 space-y-1">
            {taxRows.map(([slug, c]) => (
              <div key={slug} className="flex items-center justify-between text-sm">
                <Link href={`/leaderboard?champion=${slug}`} className="truncate text-muted hover:text-text">
                  {c.name}
                </Link>
                <span className={`tabular-nums ${Number(c.legendaryTax) >= 0 ? "text-accent" : "text-bad"}`}>
                  {Number(c.legendaryTax) >= 0 ? "+" : ""}{Number(c.legendaryTax).toFixed(1)}pp
                </span>
              </div>
            ))}
          </div>
        </Card>

        <Card className="p-5">
          <p className="text-xs font-semibold uppercase tracking-wide text-muted">
            Dedication index
          </p>
          <p className="mt-1 text-xs text-faint">
            Median ranked games a top-50 spot costs on each board.
          </p>
          <div className="mt-3 space-y-1">
            {dedication.map(([slug, c]) => (
              <div key={slug} className="flex items-center gap-2 text-sm">
                <Link href={`/leaderboard?champion=${slug}`} className="w-36 truncate text-muted hover:text-text">
                  {c.name}
                </Link>
                <span className="h-2 rounded-full bg-gold/60"
                  style={{ width: `${Math.max(3, Number(c.gamesMedian) / 1.4)}px` }} />
                <span className="text-xs tabular-nums text-muted">{c.gamesMedian}</span>
              </div>
            ))}
          </div>
        </Card>
      </div>

      <p className="mt-3 text-xs text-faint">
        More boards join with every collection run. See the{" "}
        <Link href="/hall-of-fame" className="text-accent hover:underline">Hall of Fame</Link>
        {" "}for the individual record holders.
      </p>
    </div>
  );
}
