import Link from "next/link";
import { SectionHeading, Card } from "@/components/ui";
import pulse from "@/data/ladder_pulse.json";
import items from "@/data/items.json";

// What the freshly scraped top-50 boards agree on, aggregated across every
// champion collected so far. Regenerated by scripts/build_ladder_pulse.py.

type ChampProfile = {
  name: string; avgWr: number | null; kda: number | null; teamfight: number | null;
  gpm: number | null; dmgDealt: number | null; dmgTaken: number | null;
  turret: number | null; firstBlood: number | null; mvpRate: number | null;
  sRate: number | null;
  gamesMedian: number | null; legendaryTax: number | null;
  legendaryTaxN?: number | null; pentas: number;
  /** Ranked-tier composition of the board, keyed by tier family. */
  tiers: Record<string, number>;
};

/** The two summits of the standard ladder. Legendary Ranked families are shown
 *  as their own chip rather than summed in: it is a separate queue's ladder,
 *  and adding its counts to Sovereign's would rank the two ladders as one. */
const eliteCount = (t: Record<string, number> | undefined) =>
  (t?.sovereign ?? 0) + (t?.challenger ?? 0);
const legendaryCount = (t: Record<string, number> | undefined) =>
  Object.entries(t ?? {}).reduce((a, [k, v]) => a + (k.startsWith("legendary") ? v : 0), 0);

function itemIconMap(): Record<string, string> {
  const map: Record<string, string> = {};
  for (const it of items as { slug: string; icon?: string }[]) {
    if (it.icon) map[it.slug] = it.icon;
  }
  return map;
}

function extreme(
  champs: [string, ChampProfile][],
  key: keyof ChampProfile,
  dir: "max" | "min" = "max",
): { slug: string; c: ChampProfile } | null {
  const rows = champs.filter(([, c]) => typeof c[key] === "number");
  if (!rows.length) return null;
  rows.sort((a, b) => (Number(b[1][key]) - Number(a[1][key])) * (dir === "max" ? 1 : -1));
  return { slug: rows[0][0], c: rows[0][1] };
}

export function LadderPulseSection({ championIcons }: { championIcons: Record<string, string> }) {
  const icons = itemIconMap();
  const champs = Object.entries(pulse.champions as Record<string, ChampProfile>);
  if (!champs.length) return null;

  const ksTotal = pulse.keystoneMeta.reduce((a, k) => a + k.count, 0);
  const spTotal = pulse.spellMeta.reduce((a, s) => a + s.count, 0);

  const extremes: { label: string; key: keyof ChampProfile; dir?: "max" | "min"; fmt: (v: number) => string }[] = [
    { label: "Highest damage", key: "dmgDealt", fmt: (v) => `${Math.round(v / 100) / 10}k per match` },
    { label: "Biggest tank", key: "dmgTaken", fmt: (v) => `${Math.round(v / 100) / 10}k soaked` },
    { label: "Turret menace", key: "turret", fmt: (v) => `${Math.round(v).toLocaleString()} to turrets` },
    { label: "Teamfight core", key: "teamfight", fmt: (v) => `${v.toFixed(1)}% presence` },
    { label: "First blood king", key: "firstBlood", fmt: (v) => `${v.toFixed(1)}% of games` },
    { label: "Richest", key: "gpm", fmt: (v) => `${Math.round(v)} gold per minute` },
    { label: "MVP factory", key: "mvpRate", fmt: (v) => `${v.toFixed(1)}% MVP rate` },
    { label: "S-rating machine", key: "sRate", fmt: (v) => `${v.toFixed(1)} S ratings per player` },
  ];

  const taxRows = champs
    .filter(([, c]) => c.legendaryTax != null)
    .sort((a, b) => Number(b[1].legendaryTax) - Number(a[1].legendaryTax));

  const dedication = [...champs]
    .filter(([, c]) => c.gamesMedian != null)
    .sort((a, b) => Number(b[1].gamesMedian) - Number(a[1].gamesMedian));

  // Bars are a PERCENTAGE of the longest grind, not a pixel count. The old
  // `gamesMedian / 1.4` reached 179px, which with the name column overflowed
  // the card on a 375px screen; a percentage scales to whatever width the card
  // actually has.
  const longestGrind = Math.max(1, ...dedication.map(([, c]) => Number(c.gamesMedian) || 0));
  const dedicationRow = ([slug, c]: (typeof dedication)[number]) => (
    <div key={slug} className="flex items-center gap-2 text-sm">
      <Link href={`/leaderboard?champion=${slug}`} className="w-24 shrink-0 truncate text-muted hover:text-text sm:w-36">
        {c.name}
      </Link>
      <span className="min-w-0 flex-1">
        <span
          className="block h-2 rounded-full bg-gold/60"
          style={{ width: `${Math.max(3, (Number(c.gamesMedian) / longestGrind) * 100)}%` }}
        />
      </span>
      <span className="shrink-0 text-xs tabular-nums text-muted">{c.gamesMedian}</span>
    </div>
  );

  // Boards ranked by how much of the ladder's summit sits on them.
  const stacked = [...champs]
    .filter(([, c]) => eliteCount(c.tiers) > 0)
    .sort((a, b) =>
      eliteCount(b[1].tiers) - eliteCount(a[1].tiers)
      || legendaryCount(b[1].tiers) - legendaryCount(a[1].tiers))
    .slice(0, 10);
  const pentaBoards = [...champs]
    .filter(([, c]) => (c.pentas ?? 0) > 0)
    .sort((a, b) => (b[1].pentas ?? 0) - (a[1].pentas ?? 0))
    .slice(0, 10);
  const maxPentas = pentaBoards.length ? pentaBoards[0][1].pentas : 1;

  return (
    <div className="mt-10">
      <SectionHeading
        title="Ladder pulse"
        subtitle={`Measured from ${pulse.nPlayers.toLocaleString()} top-50 players and ${pulse.nBuilds.toLocaleString()} live builds across ${pulse.nChampions} freshly collected boards`}
        href="/leaderboard"
        linkLabel="Browse the boards"
      />

      <div className="grid gap-4 lg:grid-cols-2 [&>*]:min-w-0">
        <Card className="p-5">
          <p className="text-xs font-semibold uppercase tracking-wide text-muted">
            Most equipped items in high elo
          </p>
          <div className="mt-3 flex flex-wrap gap-3">
            {pulse.itemMeta.slice(0, 12).map((it) => (
              <span key={it.slug} className="flex flex-col items-center gap-1" title={it.name}>
                {icons[it.slug] ? (
                  // eslint-disable-next-line @next/next/no-img-element
                  <img src={icons[it.slug]} alt={it.name} width={34} height={34}
                    className="h-[34px] w-[34px] rounded-md border border-line/70 bg-black/30 object-cover" />
                ) : (
                  <span className="grid h-[34px] w-[34px] place-items-center rounded-md border border-line bg-white/5 text-[0.6rem] text-faint">?</span>
                )}
                <span className="text-[0.65rem] tabular-nums text-faint">{it.count}</span>
              </span>
            ))}
          </div>
        </Card>

        <Card className="p-5">
          <p className="text-xs font-semibold uppercase tracking-wide text-muted">
            Keystone meta share
          </p>
          <div className="mt-3 space-y-1.5">
            {pulse.keystoneMeta.slice(0, 6).map((k) => (
              <div key={k.name} className="flex items-center gap-2 text-sm">
                <span className="w-40 truncate">{k.name}</span>
                <span className="h-2 rounded-full bg-accent/70"
                  style={{ width: `${Math.max(3, (k.count / ksTotal) * 220)}px` }} />
                <span className="text-xs tabular-nums text-muted">
                  {Math.round((k.count / ksTotal) * 100)}%
                </span>
              </div>
            ))}
          </div>
          <p className="mt-4 text-xs font-semibold uppercase tracking-wide text-muted">Spell pairs</p>
          <p className="mt-1.5 text-sm text-muted">
            {pulse.spellMeta.slice(0, 3).map((s, i) => (
              <span key={s.pair}>
                {i > 0 && " · "}
                <span className="text-text">{s.pair}</span>{" "}
                <span className="text-xs text-faint">{Math.round((s.count / spTotal) * 100)}%</span>
              </span>
            ))}
          </p>
        </Card>
      </div>

      <div className="mt-4 grid gap-3 sm:grid-cols-2 lg:grid-cols-3 [&>*]:min-w-0">
        {extremes.map(({ label, key, dir, fmt }) => {
          const hit = extreme(champs, key, dir);
          if (!hit) return null;
          return (
            <Card key={label} className="flex items-center gap-3 p-4">
              {championIcons[hit.slug] && (
                // eslint-disable-next-line @next/next/no-img-element
                <img src={championIcons[hit.slug]} alt="" width={36} height={36}
                  className="h-9 w-9 rounded-full object-cover ring-1 ring-white/15" />
              )}
              <div className="min-w-0">
                <p className="text-[0.65rem] font-semibold uppercase tracking-wide text-muted">{label}</p>
                <p className="truncate text-sm font-medium">
                  <Link href={`/leaderboard?champion=${hit.slug}`} className="hover:text-accent">
                    {hit.c.name}
                  </Link>
                  <span className="ml-1.5 text-xs text-faint">{fmt(Number(hit.c[key]))}</span>
                </p>
              </div>
            </Card>
          );
        })}
      </div>

      <div className="mt-4 grid gap-4 lg:grid-cols-2 [&>*]:min-w-0">
        <Card className="p-5">
          <p className="text-xs font-semibold uppercase tracking-wide text-muted">
            The Legendary tax
          </p>
          <p className="mt-1 text-xs text-faint">
            The same players, both queues: each player&apos;s Legendary Ranked win rate minus
            their own ranked one (10+ games in each), averaged per champion. Positive means
            the champion holds up at the top.
          </p>
          <div className="mt-3 space-y-1">
            {taxRows.slice(0, 5).map(([slug, c]) => (
              <div key={slug} className="flex items-center justify-between text-sm">
                <Link href={`/leaderboard?champion=${slug}`} className="min-w-0 truncate text-muted hover:text-text">
                  {c.name}
                </Link>
                <span className={`shrink-0 tabular-nums ${Number(c.legendaryTax) >= 0 ? "text-accent" : "text-bad"}`}>
                  {Number(c.legendaryTax) >= 0 ? "+" : ""}{Number(c.legendaryTax).toFixed(1)}pp
                  <span className="ml-1.5 text-[0.65rem] text-faint">{c.legendaryTaxN}p</span>
                </span>
              </div>
            ))}
          </div>
          {taxRows.length > 5 && (
            <details className="group mt-2">
              <summary className="cursor-pointer list-none text-xs font-semibold text-accent hover:underline">
                <span className="group-open:hidden">Show all {taxRows.length} champions</span>
                <span className="hidden group-open:inline">Show less</span>
              </summary>
              <div className="mt-2 space-y-1">
                {taxRows.slice(5).map(([slug, c]) => (
                  <div key={slug} className="flex items-center justify-between text-sm">
                    <Link href={`/leaderboard?champion=${slug}`} className="min-w-0 truncate text-muted hover:text-text">
                      {c.name}
                    </Link>
                    <span className={`shrink-0 tabular-nums ${Number(c.legendaryTax) >= 0 ? "text-accent" : "text-bad"}`}>
                      {Number(c.legendaryTax) >= 0 ? "+" : ""}{Number(c.legendaryTax).toFixed(1)}pp
                      <span className="ml-1.5 text-[0.65rem] text-faint">{c.legendaryTaxN}p</span>
                    </span>
                  </div>
                ))}
              </div>
            </details>
          )}
        </Card>

        <Card className="p-5">
          <p className="text-xs font-semibold uppercase tracking-wide text-muted">
            Dedication index
          </p>
          <p className="mt-1 text-xs text-faint">
            Median ranked games a top-50 spot costs on each board.
          </p>
          {/* Top five, the rest behind a disclosure. This card used to render
              all {dedication.length} champions, which made it by far the
              tallest thing on the page and buried everything below it. */}
          <div className="mt-3 space-y-1">
            {dedication.slice(0, 5).map(dedicationRow)}
          </div>
          {dedication.length > 5 && (
            <details className="group mt-2">
              <summary className="cursor-pointer list-none text-xs font-semibold text-accent hover:underline">
                <span className="group-open:hidden">Show all {dedication.length} champions</span>
                <span className="hidden group-open:inline">Show less</span>
              </summary>
              <div className="mt-2 space-y-1">{dedication.slice(5).map(dedicationRow)}</div>
            </details>
          )}
        </Card>
      </div>

      <div className="mt-4 grid gap-4 lg:grid-cols-2 [&>*]:min-w-0">
        <Card className="p-5">
          <p className="text-xs font-semibold uppercase tracking-wide text-muted">
            Most stacked boards
          </p>
          <p className="mt-1 text-xs text-faint">
            Where the ladder&apos;s summit plays: Sovereign and Challenger players per board,
            with the Legendary Ranked queue counted separately.
          </p>
          <div className="mt-3 space-y-1">
            {stacked.map(([slug, c]) => (
              <div key={slug} className="flex items-center justify-between gap-2 text-sm">
                <Link href={`/leaderboard?champion=${slug}`} className="min-w-0 truncate text-muted hover:text-text">
                  {c.name}
                </Link>
                <span className="flex shrink-0 items-center gap-1.5 text-xs tabular-nums">
                  {(c.tiers?.sovereign ?? 0) > 0 && (
                    <span className="rounded bg-gold/15 px-1.5 py-0.5 font-semibold text-gold">
                      {c.tiers.sovereign} SOV
                    </span>
                  )}
                  <span className="rounded bg-accent/15 px-1.5 py-0.5 font-semibold text-accent">
                    {c.tiers?.challenger ?? 0} CHA
                  </span>
                  {legendaryCount(c.tiers) > 0 && (
                    <span className="rounded bg-white/[0.07] px-1.5 py-0.5 text-muted">
                      {legendaryCount(c.tiers)} LGD
                    </span>
                  )}
                </span>
              </div>
            ))}
          </div>
        </Card>

        <Card className="p-5">
          <p className="text-xs font-semibold uppercase tracking-wide text-muted">
            Pentakill boards
          </p>
          <p className="mt-1 text-xs text-faint">
            Ranked pentakills this season across each board&apos;s top 50, from their
            account stats pages.
          </p>
          <div className="mt-3 space-y-1">
            {pentaBoards.map(([slug, c]) => (
              <div key={slug} className="flex items-center gap-2 text-sm">
                <Link href={`/leaderboard?champion=${slug}`} className="w-36 truncate text-muted hover:text-text">
                  {c.name}
                </Link>
                <span className="h-2 rounded-full bg-bad/60"
                  style={{ width: `${Math.max(4, (c.pentas / maxPentas) * 190)}px` }} />
                <span className="text-xs tabular-nums text-muted">{c.pentas}</span>
              </div>
            ))}
          </div>
        </Card>
      </div>

      <p className="mt-3 text-xs text-faint">
        More boards join with every collection run. See the{" "}
        <Link href="/hall-of-fame" className="text-accent hover:underline">Hall of Fame</Link>
        {" "}for the individual record holders.
      </p>
    </div>
  );
}
